# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: utf8
  host: localhost
  min_messages: warning
  pool: 20
  timeout: 5000

development:
  <<: *default
  database: spotify_api_development

test:
  <<: *default
  database: spotify_api_test
