# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6cf62a56f6ad86182c04a0898ba76e8cd37c99cb0ebdb98a49c5fdd3494119196cc48ba067639e39fa882953dc07b6cac3a5a2ec421217f32aba1da53a11249f

test:
  secret_key_base: 3a539c080fc7a9cb66c5e009da644aca062b586ee70c90de869c891fff0618bd5c78a11be652894d8aca8b63050f5ca9584ddc07881b5a4fd47698087c7d4762

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
